require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NestedGroups:
  Max: 4

