language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - ruby --version | grep '^ruby 2\.3\.' > /dev/null || gem install rubocop
  - npm install avataaars react react-dom

script:
  - ruby --version | grep '^ruby 2\.3\.' > /dev/null || rubocop
  - bundle exec rspec
