language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - gem install rubocop
  - npm install avataaars react react-dom

script:
  - rubocop
  - bundle exec rspec
